Update makefile.yml

diff --git a/.github/workflows/makefile.yml b/.github/workflows/makefile.yml
--- a/.github/workflows/makefile.yml
+++ b/.github/workflows/makefile.yml
@@ -20,6 +20,6 @@ jobs:
         distribution: 'full'
         version: 8.11.1
     - name: Check files
-      run: test -e path/to/file && echo "Test file exists" || echo "Test file does not exist"
+      run: test -e run-tests.rkt && echo "Test file exists" >> $GITHUB_STEP_SUMMARY || echo "Test file does not exist" >> $GITHUB_STEP_SUMMARY
     - name: Run check
-      run: racket run-tests.rkt
+      run: racket run-tests.rkt | grep -q '0 failure(s) 0 error(s)' && echo "All tests passed successfully." >> $GITHUB_STEP_SUMMARY || echo "Some tests failed." >> $GITHUB_STEP_SUMMARY
