making tests work

diff --git a/.github/workflows/makefile.yml b/.github/workflows/makefile.yml
--- a/.github/workflows/makefile.yml
+++ b/.github/workflows/makefile.yml
@@ -13,13 +13,29 @@ jobs:
     steps:
     - name: Checkout
       uses: actions/checkout@v2
+
     - name: Setup Racket environment
       uses: Bogdanp/setup-racket@v1.11
       with:
         architecture: 'x64'
         distribution: 'full'
         version: 8.11.1
+
     - name: Check files
-      run: test -e run-tests.rkt && echo "Test file exists" >> $GITHUB_STEP_SUMMARY || echo "Test file does not exist" >> $GITHUB_STEP_SUMMARY
+      run: |
+        if test -e run-tests.rkt; then 
+          echo "Test file exists" >> $GITHUB_STEP_SUMMARY
+        else 
+          echo "Test file does not exist" >> $GITHUB_STEP_SUMMARY
+          exit 1
+        fi
+
     - name: Run check
-      run: racket run-tests.rkt | grep -q '0 failure(s) 0 error(s)' && echo "All tests passed successfully." >> $GITHUB_STEP_SUMMARY || echo "Some tests failed." >> $GITHUB_STEP_SUMMARY
+      run: |
+        racket run-tests.rkt | tee /dev/tty | grep -q '0 failure(s) 0 error(s)'
+        if [ $? -ne 0 ]; then
+          echo "Some tests failed." >> $GITHUB_STEP_SUMMARY
+          exit 1
+        else
+          echo "All tests passed successfully." >> $GITHUB_STEP_SUMMARY
+        fi
